channels:
  - conda-forge

name:
  - nltools >= 0.3.17

dependencies:
  - python >= 3.6
  - pip:
    - sphinx >= 1.5
    - sphinx-gallery
    - sphinxcontrib-napoleon
    - sphinx_bootstrap_theme
    - networkx
